version: '3'

services:
  farm-client:
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=developement
    command: pnpm dev --host
    